# Generated by Django 3.1.3 on 2020-11-23 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tjbh', models.CharField(blank=True, max_length=300, null=True)),
                ('andetail', models.CharField(blank=True, max_length=3000, null=True)),
                ('answerer', models.CharField(blank=True, max_length=3000, null=True)),
                ('getscore', models.IntegerField(blank=True, default=0, null=True)),
                ('antime', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(blank=True, max_length=300, null=True)),
                ('questionid', models.CharField(blank=True, max_length=300, null=True)),
                ('tjbh', models.CharField(blank=True, max_length=300, null=True)),
                ('wtms', models.CharField(blank=True, max_length=3000, null=True)),
                ('rtype', models.CharField(blank=True, max_length=3000, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('stdnb', models.CharField(blank=True, max_length=30, null=True)),
                ('create_week1time', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdnb', models.CharField(blank=True, max_length=30, null=True)),
                ('stuname', models.CharField(blank=True, max_length=30, null=True)),
                ('count', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestWJL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youarefree', models.CharField(max_length=1000, null=True)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('personname', models.CharField(blank=True, max_length=30, null=True)),
                ('ranking', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('store', models.IntegerField(blank=True, default=0, null=True)),
                ('qcount', models.IntegerField(blank=True, default=0, null=True)),
                ('acount', models.IntegerField(blank=True, default=0, null=True)),
                ('Answer_ID', models.ManyToManyField(max_length=30, to='OJ_app.Answer')),
                ('Question_ID', models.ManyToManyField(max_length=30, to='OJ_app.Question')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='userToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='OJ_app.user')),
            ],
            options={
                'verbose_name': '用户token表',
                'verbose_name_plural': '用户token表',
                'db_table': 'user_token',
            },
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('personname', models.CharField(blank=True, max_length=30, null=True)),
                ('ranking', models.CharField(max_length=30)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('store', models.IntegerField(blank=True, default=0, null=True)),
                ('qcount', models.IntegerField(blank=True, default=0, null=True)),
                ('acount', models.IntegerField(blank=True, default=0, null=True)),
                ('Answer_ID', models.ManyToManyField(max_length=30, to='OJ_app.Answer')),
                ('Question_ID', models.ManyToManyField(max_length=30, to='OJ_app.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=3000)),
                ('creates_time', models.TimeField()),
                ('Reviewers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
