# Generated by Django 3.1.3 on 2020-11-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='Answer_ID',
            field=models.ManyToManyField(blank=True, max_length=30, null=True, to='OJ_app.Answer'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='Question_ID',
            field=models.ManyToManyField(blank=True, max_length=30, null=True, to='OJ_app.Question'),
        ),
    ]
